export const DataLocalidades = [
  { name: "Formosa Capital" },
  { name: "El Colorado" },
  { name: "Clorinda" },
  { name: "Laguna Blanca" },
  { name: "General Belgrano" },
  {name:  "Ingeniero Juaréz"},
];

export const DataBarrios = {
  "Formosa Capital": [
    { name: "12 DE OCTUBRE", houses: 526 },
    { name: "2 DE ABRIL", houses: 1022 },
    { name: "BARRIO MILITAR", houses: 119 },
    { name: "OBRERO", houses: 1401 },
    { name: "BARRIO VIAL", houses: 958 },
    { name: "DON BOSCO", houses: 1606 },
    { name: "EL MISTOL", houses: 98 },
    { name: "EL RESGUARDO", houses: 513 },
    { name: "MANUEL BELGRANO", houses: 71 },
    { name: "EMILIO TOMAS", houses: 340 },
    { name: "EVA PERÓN", houses: 2200 },
    { name: "GUADALUPE", houses: 1435 },
    { name: "INDEPENDENCIA", houses: 1462 },
    { name: "J.F. KENNEDY", houses: 90 },
    { name: "JUAN D. PERÓN", houses: 1143 },
    { name: "LA FLORESTA", houses: 831 },
    { name: "LAS DELICIAS", houses: 213 },
    { name: "LIBORSI", houses: 714 },
    { name: "MARIANO MORENO", houses: 1636 },
    { name: "NANQOM", houses: 433 },
    { name: "SAN AGUSTÍN", houses: 780 },
    { name: "SAN FRANCISCO", houses: 2222 },
    { name: "SAN JOSÉ OBRERO", houses: 741 },
    { name: "SAN MARTÍN", houses: 3814 },
    { name: "SAN MIGUEL", houses: 1333 },
    { name: "SAN PEDRO", houses: 743 },
    { name: "SANTA ROSA", houses: 421 },
    { name: "SIMÓN BOLIVAR", houses: 2161 },
    { name: "VENEZUELA", houses: 619 },
    { name: "VILLA DEL ROSARIO", houses: 1106 },
    { name: "VILLA HERMOSA", houses: 505 },
    { name: "VILLA LA PILAR", houses: 954 },
    { name: "VILLA LOURDES", houses: 1244 },
    { name: "VIRGEN DE LUJÁN", houses: 316 },
    { name: "LA ESPERANZA", houses: 180 },
    { name: "7 DE MAYO", houses: 368 },
    { name: "ANTENOR GAUNA", houses: 1069 },
    { name: "1° DE MAYO", houses: 184 },
    { name: "EL PORVENIR", houses: 352 },
    { name: "BERNARDINO RIVADAVIA", houses: 890 },
    { name: "VIRGEN DE ITATÍ", houses: 782 },
    { name: "PARQUE INDUSTRIAL", houses: 27 },
    { name: "SAN JUAN BAUTISTA", houses: 671 },
    { name: "16 DE JULIO", houses: 73 },
    { name: "SAG. CORAZÓN DE MARÍA", houses: 100 },
    { name: "ARTURO ILLIA", houses: 935 },
    { name: "HIPÓLITO IRIGOYEN", houses: 193 },
    { name: "SAN CAYETANO", houses: 217 },
    { name: "FACUNDO QUIROGA", houses: 82 },
    { name: "SAN ANDRES", houses: 177 },
    { name: "SANTA LUCÍA", houses: 101 },
    { name: "LA VIRGEN NIÑA", houses: 184 },
    { name: "17 DE OCTUBRE", houses: 123 },
    { name: "LIBERTAD", houses: 129 },
    { name: "ISLAS MALVINAS", houses: 197 },
    { name: "COLLUCCIO", houses: 443 },
    { name: "SAN ISIDRO LABRADOR", houses: 396 },
    { name: "ROBERTO SOTELO", houses: 133 },
    { name: "8 DE MARZO", houses: 226 },
    { name: "CO.VI.FOL.", houses: 124 },
    { name: "FONTANA", houses: 1232 },
    { name: "SOLANO LIMA", houses: 217 },
    { name: "LA ESTRELLA", houses: 53 },
    { name: "20 de JULIO", houses: 225 },
    { name: "REPÚBLICA ARGENTINA", houses: 1895 },
    { name: "8 DE OCTUBRE", houses: 344 },
    { name: "EL QUEBRANTO", houses: 152 },
    { name: "EL QUEBRACHITO", houses: 450 },
    { name: "EL PALOMAR", houses: 493 },
    { name: "STELLA MARIS", houses: 216 },
    { name: "LOS INMIGRANTES", houses: 112 },
    { name: "LAS ORQUIDEAS", houses: 275 },
    { name: "Dr. RICARDO BALBÍN", houses: 170 },
    { name: "SAN JUAN", houses: 316 },
    { name: "SAN ANTONIO", houses: 454 },
    { name: "PARQUE URBANO", houses: 522 },
    { name: "ARTURO ILLIA II", houses: 670 },
    { name: "YAPEYÚ", houses: 536 },
    { name: "8 DE OCTUBRE BIS", houses: 234 },
    { name: "CARACOLITO", houses: 278 },
    { name: "CONO SUR", houses: 182 },
    { name: "EL PALMAR", houses: 268 },
    { name: "EL PUCÚ", houses: 321 },
    { name: "EL TIMBÓ I", houses: 156 },
    { name: "EL TIMBÓ II", houses: 299 },
    { name: "EVITA", houses: 205 },
    { name: "FEDERACIÓN", houses: 221 },
    { name: "FLEMING", houses: 169 },
    { name: "GUAYAIBÍ", houses: 304 },
    { name: "ITATÍ I", houses: 150 },
    { name: "ITATÍ II", houses: 277 },
    { name: "JUAN MANUEL DE ROSAS", houses: 189 },
    { name: "LA PAZ", houses: 253 },
    { name: "MALVINAS", houses: 212 },
    { name: "NUEVA FORMOSA", houses: 184 },
    { name: "NUEVA POMPEYA", houses: 322 },
    { name: "PARQUE URBANO I", houses: 305 },
    { name: "PARQUE URBANO II", houses: 185 },
    { name: "SAN PÍO X", houses: 257 },
    { name: "SAN JOSÉ OBRERO", houses: 311 },
    { name: "SARMIENTO", houses: 278 },
    { name: "URUNDAY", houses: 226 },
    { name: "VILLA JARDÍN", houses: 300 },
    { name: "VIRGEN DEL CARMEN", houses: 245 },
    { name: "VIRGEN NUESTRA SEÑORA DEL PILAR", houses: 178 },
    { name: "LOTE 4", houses: 158 },
    { name: "LUJAN", houses: 274 },
    { name: "ZONA RURAL", houses: 783 },
  ],
  Colorado: [
    { name: "CENTRO", houses: 287 },
    { name: "OBRERO", houses: 384 },
    { name: "SAN MIGUEL", houses: 431 },
    { name: "SAN FRANCISCO", houses: 308 },
  ],
  "General Belgrano": [
    { name: "CENTRO", houses: 391 },
    { name: "40 VIVIENDAS", houses: 492 },
    { name: "12 DE OCTUBRE", houses: 359 },
  ],
  "Laguna Blanca": [
    { name: "CENTRO", houses: 406 },
    { name: "SAN JUAN", houses: 481 },
    { name: "SAN MIGUEL", houses: 532 },
    { name: "BELGRANO", houses: 357 },
  ],
  Clorinda: [
    { name: "CENTRO", houses: 512 },
    { name: "25 DE MAYO", houses: 401 },
    { name: "LIBERTAD", houses: 535 },
    { name: "PORTEÑO NORTE", houses: 296 },
    { name: "240 VIVIENDAS", houses: 452 },
  ],
  "Ingeniero Juaréz": [
    { name: "CENTRO", houses: 513 },
    { name: "Villa Hermosa", houses: 412 },
    { name: "San Cayetano", houses: 536 },
    { name: "Toba", houses: 297 },
    { name: "50 VIVIENDAS", houses: 453 },
  ],
};
