export const DataMaterias = {
  Primaria: [
    { name: "MATEMÁTICAS" },
    { name: "LENGUA Y LITERATURA" },
    { name: "CIENCIAS SOCIALES" },
    { name: "CIENCIAS NATURALES" },
    { name: "INGLES" },
    { name: "PLASTICA Y ARTISTICA" },
    { name: "EDUCACION FISICA" },
    { name: "GEOGRAFIA" },
  ],
  Secundaria: [
    { name: "ALGEBRA Y ARITMETICA" },
    { name: "TECNOLOGIA" },
    { name: "LENGUA Y LITERATURA" },
    { name: "ECONOMIA" },
    { name: "QUIMICA" },
    { name: "FISICA" },
    { name: "INGLES" },
    { name: "PLASTICA Y ARTISTICA" },
    { name: "BIOLOGIA" },
    { name: "HISTORIA CONTEMPORANEA" },
    { name: "EDUCACION FISICA" },
    { name: "ETICA Y CIUDADANIA" },
  ],
  Terciario: [
    { name: "BASE DE DATOS" },
    { name: "ALGORITMOS" },
    { name: "TALLER DE LENGUAJE DE PROGRAMACION" },
    { name: "PROYECTO INTEGRADOR" },
    { name: "MATEMATICA APLICADA" },
    { name: "VALORES CIUDADANOS" },
    { name: "INGLES" },
    { name: "MINERIA DE DATOS" },
    { name: "ARQUITECTURA Y SO" },
    { name: "TECNOLOGIA Y SOCIEDAD" },
  ],
};
