export const DataModalidadesSecundaria = [
  { name: "Humanidades y Ciencias Sociales" },
  { name: "Ciencias Naturales" },
  { name: "Economía y Comercio" },
  { name: "Ciclo Básico Básico Técnico" },
  { name: "Ciclo Básico Artístico" },
  { name: "Ciclo Básico Artístico Pirané" },
  { name: "Ciclo Secundario Orientado en Agro y Ambiente " },
  { name: "Comercial Nocturno " },
  { name: "Economía y Gestión de las Organizaciones " },
  {
    name: "Ciclo Orientado EPES 52 Polivalente de Arte y EPES 89 Polivalente de Arte Pirané ",
  },
  { name: "Técnico Mecánico " },
  { name: "Desarrollo de Software Multiplataforma " },
  { name: "Maestro Mayor de Obras" },
  { name: "Técnico en Salud y Ambiente " },
  { name: "Técnico en Tecnología de los Alimentos" },
  { name: "Técnico Químico " },
  { name: "Técnico en Mecanización Agropecuaria " },
  { name: "Técnico en Automotores " },
  { name: "Técnico en Electrónica " },
  { name: "Técnico en Informática Profesional y Personal" },
  { name: "Tecnico en Telecomunicacion" },
];
